-- GüvenCheck V0.8.x — anonymous beta analytics + Phase 0 economic readiness
-- Supabase Dashboard > SQL Editor > New query içine yapıştırıp Run edin.

create table if not exists public.beta_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view','analysis_started','analysis_completed','analysis_error','share_clicked','privacy_view','analysis_feedback')),
  session_id text,
  analysis_type text check (analysis_type is null or analysis_type in ('text','link','image')),
  score smallint check (score is null or (score >= 0 and score <= 100)),
  risk_level text check (risk_level is null or risk_level in ('low','medium','high')),
  model_route text,
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  helpful boolean,
  feedback_reason text check (feedback_reason is null or feedback_reason in ('dogru','fazla_supheci','riski_az_gosterdi','anlasilmadi','diger')),
  analysis_request_id text
);

alter table public.beta_events enable row level security;
revoke all on table public.beta_events from anon, authenticated;
grant all on table public.beta_events to service_role;
grant usage, select on sequence public.beta_events_id_seq to service_role;

create index if not exists beta_events_created_at_idx on public.beta_events (created_at desc);
create index if not exists beta_events_session_id_idx on public.beta_events (session_id);
create index if not exists beta_events_event_type_idx on public.beta_events (event_type);

comment on table public.beta_events is 'GüvenCheck anonymous beta product analytics; message/link/image content is never stored here.';

-- Phase 0 economic telemetry. No analyzed content, URL, image or message body is stored.
create table if not exists public.economic_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  analysis_request_id text not null,
  analysis_type text check (analysis_type is null or analysis_type in ('text','link','image')),
  provider text not null default 'openai',
  model text,
  model_route text,
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  cached_input_tokens integer check (cached_input_tokens is null or cached_input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  total_tokens integer check (total_tokens is null or total_tokens >= 0),
  web_search_calls integer check (web_search_calls is null or web_search_calls >= 0),
  estimated_cost_usd numeric(14,6) check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  success boolean not null,
  error_class text
);

alter table public.economic_events enable row level security;
revoke all on table public.economic_events from anon, authenticated;
grant all on table public.economic_events to service_role;
grant usage, select on sequence public.economic_events_id_seq to service_role;

create unique index if not exists economic_events_request_id_idx on public.economic_events (analysis_request_id);
create index if not exists economic_events_created_at_idx on public.economic_events (created_at desc);
create index if not exists economic_events_success_idx on public.economic_events (success);

comment on table public.economic_events is 'GüvenCheck Phase 0 AI economic telemetry. Stores usage/cost metadata only; analyzed content is never stored.';
