-- GüvenCheck V0.7.2 — anonymous beta analytics
-- Supabase Dashboard > SQL Editor > New query içine yapıştırıp Run edin.

create table if not exists public.beta_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in ('page_view','analysis_started','analysis_completed','analysis_error','share_clicked','privacy_view','analysis_feedback')),
  session_id text,
  analysis_type text check (analysis_type is null or analysis_type in ('text','link','image')),
  score smallint check (score is null or (score >= 0 and score <= 100)),
  risk_level text check (risk_level is null or risk_level in ('low','medium','high')),
  model_route text,
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  helpful boolean,
  feedback_reason text check (feedback_reason is null or feedback_reason in ('dogru','fazla_supheci','riski_az_gosterdi','anlasilmadi','diger')),
  analysis_request_id text
);

alter table public.beta_events enable row level security;

-- Browser/anon kullanıcıların tabloya doğrudan erişimini kapat.
revoke all on table public.beta_events from anon, authenticated;
-- Backend secret key service_role yetkisiyle çalışır.
grant all on table public.beta_events to service_role;
grant usage, select on sequence public.beta_events_id_seq to service_role;

create index if not exists beta_events_created_at_idx on public.beta_events (created_at desc);
create index if not exists beta_events_session_id_idx on public.beta_events (session_id);
create index if not exists beta_events_event_type_idx on public.beta_events (event_type);

comment on table public.beta_events is 'GüvenCheck anonymous beta product analytics; message/link/image content is never stored here.';
